import os
import json
import datetime

# Resolve paths
script_dir = os.path.dirname(os.path.abspath(__file__))
base_dir = os.path.dirname(os.path.dirname(script_dir))
bible_dir = os.path.join(base_dir, "bible")
status_file = os.path.join(base_dir, "_meta", "STATUS.md")

def main():
    print("=== GENERATING REPOSITORY STATUS.MD ===")
    
    if not os.path.exists(bible_dir):
        print("Error: bible/ directory does not exist.")
        return
        
    total_languages = 0
    total_versions = 0
    total_chapters = 0
    
    version_rows = []
    detailed_sections = []
    
    # We will walk languages and versions
    for lang in sorted(os.listdir(bible_dir)):
        lang_path = os.path.join(bible_dir, lang)
        if not os.path.isdir(lang_path):
            continue
            
        total_languages += 1
        lang_name = lang.capitalize()
        
        detailed_sections.append(f"### {lang_name}")
        
        for ver in sorted(os.listdir(lang_path)):
            ver_path = os.path.join(lang_path, ver)
            if not os.path.isdir(ver_path):
                continue
                
            total_versions += 1
            
            # Read metadata.json if exists
            name = ver.upper()
            meta_path = os.path.join(ver_path, "metadata.json")
            if os.path.exists(meta_path):
                try:
                    with open(meta_path, "r", encoding="utf-8") as f:
                        meta = json.load(f)
                        name = meta.get("name", name)
                except:
                    pass
            
            # Scan testaments
            ot_path = os.path.join(ver_path, "ot")
            nt_path = os.path.join(ver_path, "nt")
            
            has_ot = os.path.exists(ot_path) and len(os.listdir(ot_path)) > 0
            has_nt = os.path.exists(nt_path) and len(os.listdir(nt_path)) > 0
            
            ot_symbol = "✅" if has_ot else "⬜"
            nt_symbol = "✅" if has_nt else "⬜"
            
            # Count books and chapters
            books_count = 0
            chapters_count = 0
            
            for testament in ["ot", "nt"]:
                t_path = os.path.join(ver_path, testament)
                if os.path.exists(t_path):
                    for book in sorted(os.listdir(t_path)):
                        book_path = os.path.join(t_path, book)
                        if os.path.isdir(book_path):
                            books_count += 1
                            for ch in os.listdir(book_path):
                                if ch.endswith(".txt"):
                                    chapters_count += 1
                                    total_chapters += 1
                                    
            # Row for overview table
            version_rows.append(
                f"| {lang_name:<12} | {ver.upper():<10} | {ot_symbol:<4} | {nt_symbol:<4} | Complete | {books_count} books, {chapters_count} chapters |"
            )
            
            # Detailed item
            detailed_sections.append(
                f"- [x] **{ver.upper()}** ({name}) — *Collected & Split ({chapters_count} chapters across {books_count} books)*"
            )
            
        detailed_sections.append("") # empty line after language
        
    # Standard pending list
    pending_rows = [
        "| Greek        | TR         | ⬜    | ✅    | Pending  | Textus Receptus (license review pending) |",
        "| Telugu       | TSI        | ⬜    | ⬜    | Pending  | Telugu Study Bible |",
        "| Hindi        | HHBD       | ⬜    | ⬜    | Pending  | Hindi Holy Bible Deluxe |"
    ]
    
    # Construct Markdown content
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    md = []
    md.append("# Bible Dataset Status")
    md.append("")
    md.append(f"*Last Updated: {timestamp}*")
    md.append("")
    md.append("This file is automatically generated based on the actual files stored in the repository.")
    md.append("")
    md.append("## Collection Overview")
    md.append("")
    md.append(f"- **Total Languages**: {total_languages}")
    md.append(f"- **Total Bible Versions**: {total_versions}")
    md.append(f"- **Total Chapters**: {total_chapters}")
    md.append("")
    md.append("## Status Matrix")
    md.append("")
    md.append("| Language     | Version    | OT   | NT   | Status   | Scope / Coverage |")
    md.append("|--------------|------------|------|------|----------|------------------|")
    md.extend(version_rows)
    md.extend(pending_rows)
    md.append("")
    md.append("---")
    md.append("")
    md.append("## Detailed Version Status")
    md.append("")
    md.extend(detailed_sections)
    md.append("## Teachings / Sermons")
    md.append("")
    md.append("- [ ] **Speaker Collections** — *No real speaker data collected yet (reserved for Phase 3)*")
    md.append("")
    
    md_content = "\n".join(md)
    
    with open(status_file, "w", encoding="utf-8") as f:
        f.write(md_content)
        
    print(f"STATUS.md updated successfully at: {status_file}")

if __name__ == "__main__":
    main()
